---
name: Checkout and set up Python
description: Checkout the repository (full history and tags) and set up Python

inputs:
  python-version:
    description: Python version to set up
    required: false
    default: "3.x"

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0
        fetch-tags: true
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: ${{ inputs.python-version }}
